name: 🐛 Bug Report
description: Report a bug or issue with the website
title: "[Bug]: "
labels: ["bug", "needs-triage"]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g., The navigation menu doesn't close on mobile when clicking a link.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g., The mobile menu should close when I click a navigation link.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: e.g., The menu stays open and I have to click the close button manually.
    validations:
      required: true

  - type: dropdown
    id: page
    attributes:
      label: Which page is affected?
      description: Select the page where you encountered the bug
      options:
        - Homepage
        - Blog listing
        - Blog post
        - Contact page
        - FAQ page
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: If applicable, provide the URL where the bug occurs
      placeholder: e.g., https://gurlscodingclub.com/blog

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other (please specify below)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., 120.0.6099.109

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop (Windows)
        - Desktop (macOS)
        - Desktop (Linux)
        - Mobile (iOS)
        - Mobile (Android)
        - Tablet (iOS)
        - Tablet (Android)
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. You can paste images directly into this field.
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: e.g., This only happens when I'm logged in, or This started happening after the recent update.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our code of conduct
      options:
        - label: I have checked existing issues to make sure this bug hasn't been reported before
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
